### ISSUE TITLE
Not able to build

### ISSUE THREAD

**Issue by eneskaya** [brendan-rius/react-native-emoji-keyboard#1]
I installed and manually linked the app by adding `RNEmojiKeyboardFramework.Framework` and `libRNEmojiKeyboard.a, and after the start I get a crash with this message:

```
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/xxx/Library/Developer/Xcode/DerivedData/xxx-xxx/Build/Products/Debug-iphonesimulator/RNEmojiKeyboardFramework.framework/RNEmojiKeyboardFramework
  Reason: image not found
```

Also tried to install the iOS Framework as pods, but still same error.

**Comment by brendan-rius** [comment]
It looks like the swift standard librairies are not included although they
are needed by the plugin. Could you please try setting the "Embedded
Content Contains Swift Code" flag to YES in your project's settings, then
clean the project and try again [as described here](
https://stackoverflow.com/a/26949219)

Thank you

**Comment by brendan-rius** [comment]
Any news on this?

**Comment by brendan-rius** [comment]
I added additional information on how to link the project in the README and it should work. Please refer to this.

DO not hesitate to re-open if your problem persists
